### ISSUE TITLE
Add possibility to authenticate via for LDAP sync

### ISSUE THREAD

**Issue by lpar** [zammad/zammad#1422]
### Infos:

 * Zammad 2.0 from RPM repo
 * CentOS 7
 * Google Chrome

### Behavior:

 * When I fill out the LDAP hostname, the first step works and I'm taken to step 2.
 * For step 2, none of the suggested base DN options in the drop-down are correct for authentication. The closest to correct is o= with no ou.
 * If I enter a valid username and password, I get "Can't connect to '[servername]' on port '389', Can't bind to '[servername]', 49, Invalid Credentials"
 * If I try entering a user DN and password instead, I get "Unable to retrive user information, please check your bind user permissions."
 * The behavior above is the same whether I use the closest suggested DN, enter the correct DN, or accept the default DN in the selector.

The frustrating thing is, I have a trivial Ruby net/ldap script which performs authentication via bind successfully, so I know the exact parameters I need and I know the server is compatible with net/ldap --  but the only way to get Zammad configured seems to be to let the "wizard" discover the parameters, and it's failing.

The production.log doesn't seem to list anything informative.

Any ideas? Is there a backdoor LDAP configuration option?

**Comment by thorsteneckel** [comment]
Hi @lpar !

"Sorry" - no backdoors 🚪 Could you please post your Ruby script without the credentials? I'll have a look to spot the differences.

Thanks for the comprehensive report!

**Comment by lpar** [comment]
```
#!/usr/bin/env ruby
# encoding: UTF-8

require 'net/ldap'
require 'pp'

def authenticate(email, password)
  ldap = Net::LDAP.new :host => "bluepages.ibm.com",
    :port => 636,
    :encryption => :simple_tls,
    :force_no_page => true

  ldap.search(:base => "ou=bluepages,o=ibm.com",
    :filter => "(&(objectClass=person)(mail=#{email}))",
    :attributes => ["dn","givenname","sn","mail"]) do |entry|
    puts "Found user, DN: #{entry.dn}"
    pp entry
    if ldap.bind(:method => :simple, :username => entry.dn, :password => password)
      puts "Authentication succeeded"
      return true
    else
      puts "Bad password"
      return false
    end
  end
  puts "No such user #{email}"
  return false
end

puts authenticate("username@us.ibm.com", "passwordhere")
```

Now that I look at it, I remember one issue is the `:force_no_page => true` parameter, because there's some strange incompatibility between Net::LDAP and paging mode with our LDAP server. You shouldn't need paged results for authentication anyway, of course.

**Comment by thorsteneckel** [comment]
Hi mathew,

nice. This clears things up. I think I've spot the difference. Your code performs an anonymous bind to lookup the `dn` for the given `email`. Since we want to support as many LDAPs as possible we can't rely on an anonymous bind. Some people deactivate those for a reasonable cause. That's why we expect the admin to enter the `dn` instead of the email.

I totally agree with you that this is not clear at the moment. I agree that Zammad should check if the given "username" looks like an email and try to perform an anonymous bind. If it fails Zammad still can notify the admin to insert the `dn`. What do you think?

We currently have other priorities on our so a change might take some time. I'll change the title and add some labels to make that clear. I see you have some Ruby skills over there 🤓 would be great to see a Pull Request for this 🦅 The right place would be [over here](https://github.com/zammad/zammad/blob/develop/lib/ldap.rb#L130).

**Comment by lpar** [comment]
Aha, so it _is_ supposed to be a bind DN and not a bind user.

It still doesn't work if I enter the bind DN, though. I get "Unable to retrive user information, please check your bind user permissions."

**Comment by thorsteneckel** [comment]
Can you please check the following script:

```ruby
#!/usr/bin/env ruby
# encoding: UTF-8

require 'net/ldap'

def authenticate(dn, password)
  ldap = Net::LDAP.new :host => "bluepages.ibm.com",
    :port => 636,
    :encryption => :simple_tls,
    :force_no_page => true

  ldap.auth dn, password

  if ldap.bind
    puts "Authentication succeeded"
    return true
  else
    puts "Bad password"
    return false
  end
end

puts authenticate("dn here", "passwordhere")
```

**Comment by lpar** [comment]
```
Authentication succeeded
true
```

**Comment by thorsteneckel** [comment]
Okay, so the login works. So it's probably due to the filters. Which filter would be the right one in your setup?

Zammad tries the following:
- `(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))`
- `(objectClass=user)`
- `(objectClass=posixaccount)`
- `(objectClass=person)`

None of these returns a result.

**Comment by lpar** [comment]
`(objectClass=person)` is correct, it's what I use in my code.

What search is Zammad doing?

**Comment by thorsteneckel** [comment]
Hi @lpar - sorry for the delay. Does your issue still persists? If so please run my debug script as described:

1.) Create a file called `debug_ldap.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_ldap.rb` file

```ruby
bind_dn    = 'dn here'
bind_pw    = 'password here'
filter     = '(objectClass=person)'
host       = 'bluepages.ibm.com'
port       = 636
base_dn    = 'ou=bluepages,o=ibm.com'
ssl        = true
ssl_verify = true


ldap = Ldap.new(
  host:       host,
  port:       port,
  ssl:        ssl,
  ssl_verify: ssl_verify,
  base_dn:    base_dn,
  bind_user:  bind_dn,
  bind_pw:    bind_pw,
)

ldap.search(filter) do |entry|
  p entry.to_h
end
```

**Comment by lpar** [comment]
Updated to zammad-2.0.0-1508435919.accea5df.centos7.x86_64 from repo. Problem continues with 'Unable to retrive user information, please check your bind user permissions.'

Running the `debug_ldap.rb` script with `zammad run rails r debug_ldap.rb` as zammad user, I get no output.

Just to check I didn't make a mistake with any of the values, I wrote this code which uses the same variables and works:

```ruby
ldap = Net::LDAP.new :host => host, :port => port, :encryption => :simple_tls, :force_no_page => true

if !ldap.bind(:method => :simple, :username => bind_dn, :password => bind_pw)
  puts "Bind failed"
  exit 1
end

ldap.search(:base => base_dn, :filter => filter) do |entry|
  pp entry
  break
end
```

**Comment by thorsteneckel** [comment]
Thanks for your fast response. Did I get you right that the `:force_no_page => true` parameter is critical? Otherwise there won't be any output in your script as well?

**Comment by lpar** [comment]
Yes, there's some strange incompatibility between pure Ruby LDAP with paging, and our LDAP server. I mentioned this earlier, but probably not clearly enough!

**Comment by thorsteneckel** [comment]
Hi @lpar - Thanks for your fast response. I've found your comment in [this issue](https://github.com/ruby-ldap/ruby-net-ldap/issues/27) in the meantime. As I understand it this only affects `bluepages.ibm.com` right? Can you please check if the new script works?

1.) Create a file called `debug_ldap.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_ldap.rb` file

```ruby
bind_dn    = 'dn here'
bind_pw    = 'password here'
filter     = '(objectClass=person)'
host       = 'bluepages.ibm.com'
port       = 636
base_dn    = 'ou=bluepages,o=ibm.com'
ssl        = true
ssl_verify = true


require 'ldap'

class Ldap
  def connection_params
    params = {
      host: @host,
      port: @port,
    }

    if @encryption
      params[:encryption] = @encryption
    end

    if @host == 'bluepages.ibm.com'
      params[:force_no_page] = true
    end

    params
  end
end

ldap = Ldap.new(
  host:       host,
  port:       port,
  ssl:        ssl,
  ssl_verify: ssl_verify,
  base_dn:    base_dn,
  bind_user:  bind_dn,
  bind_pw:    bind_pw,
)

ldap.search(filter) do |entry|
  p entry.to_h
end
```

**Comment by lpar** [comment]
With that change, I get a ton of output. I won't send you the entire LDAP directory 😀

I guess the next step is to have it use a more sensible filter. The usual `(&(mail=login@example.com)(objectClass=person))` works.

**Comment by thorsteneckel** [comment]
Nice! As far as [I understand it](https://github.com/ruby-ldap/ruby-net-ldap/issues/27) this is an exclusive workaround for IBM bluepages. I'll add this tomorrow so you can use Zammads LDAP functionality 👍

**Comment by lpar** [comment]
My understanding is that IBM bluepages uses a commercial product, so it's likely there are other people with LDAP servers that will react badly if you demand the optional paging extension.

I assume the code closes the connection after reading the first returned result? If it reads the whole response then takes the first entry, that would be bad...

**Comment by thorsteneckel** [comment]
That's quite possible. However, I couldn't find any other entries indicating a similar behavior of other software. In the event that it reappears, we will then find a more general solution. This error is fixed with the commit. A new release should be ready in 30 minutes. It would be great if you could test it and provide some feedback. Thanks for your support!

**Comment by lpar** [comment]
I'm afraid it's still not working in the new release. After entering the base DN, bind user DN and password as above I still get `Unable to retrive user information, please check your bind user permissions.`

Log says:
```
I, [2017-10-30T14:18:04.805800 #520]  INFO -- : Processing by Integration::LdapController#bind as JSON
I, [2017-10-30T14:18:04.805898 #520]  INFO -- :   Parameters: {"base_dn"=>"ou=bluepages,o=ibm.com", "bind_user"=>"uid=REDACTED,c=us,ou=bluepages,o=ibm.com", "bind_pw"=>"[FILTERED]", "host_url"=>"ldaps://bluepages.ibm.com", "ssl_verify"=>true}
I, [2017-10-30T14:18:04.890028 #516]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2017-10-30T14:18:14.824836 #516]  INFO -- : Scheduler running...
I, [2017-10-30T14:18:16.420413 #520]  INFO -- : Completed 200 OK in 11614ms (Views: 2.1ms | ActiveRecord: 2.6ms)
```

I'm e-mailing the current state of the debug script, and sample output from it.

**Comment by thorsteneckel** [comment]
Damn. Could you please post the exact version of your package?

**Comment by lpar** [comment]
zammad-2.1.0-1509367921.b7308552.centos7.x86_64

**Comment by thorsteneckel** [comment]
Ah! I see. You are on the stable branch and I only added this to develop. I cherry-picked it to stable so please test again in ca. 30 minutes from now.

**Comment by lpar** [comment]
OK, new error. "Unable to retrive group information, please check your bind user permissions." Want a new ticket for that, as it sounds like an unrelated problem?

**Comment by thorsteneckel** [comment]
Damn. Yes, please. I'll provide a debugging script for further digging.

**Comment by LuckyLuisHD** [comment]
Hi there. I stumbled across this issue, when trying to use my Uni's LDAP Server for login into my student unions Zammad System. 

When i start the LDAP Sync only about 150 Users get synced. Every Time I sync again it puts in those same users. 

I Found out Commenting that If statement out of the ldap.rb in line150 fixes the issue. Is it possible to create a way to disable this beahvior in the config or GUI?

If you want to test it yourself, our Uni keeps their LDAP open, the config i used was: 
`hostname: ldaps://ldap.hs-augsburg.de`
`baseDN: dc=fh-augsburg,dc=de`
The UID is `uid` and the filter i used was `(&(ou=Informatik)(objectclass=inetOrgPerson)(employeeType=Studenten)(\|(schacGender=1)(schacGender=2)))`

Thanks a lot :)

**Comment by MrGeneration** [comment]
Please do not hijack issues with your technical questions. If you have technical questions or feature requests, please consult our community: https://community.zammad.org

Thank you very much.
