### ISSUE TITLE
ERROR: Can't process email

### ISSUE THREAD

**Issue by Dirk23** [zammad/zammad#2578]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): APT
* Operating system: Ubuntu 18.04
* Database + version: ?
* Elasticsearch version: ?
* Browser + version: Chrome lastest

```
~$ sudo zammad run rails r "Channel::EmailParser.process_unprocessable_mails"
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
Encoding conversion failed code converter not found (Windows-1258 to UTF-8)
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/ff6c9cae8fa9fb0cd7cb1c64b5cc2439.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ArgumentError: invalid byte sequence in UTF-8>"
/opt/zammad/app/models/channel/email_parser.rb:129:in `rescue in process': #<ArgumentError: invalid byte sequence in UTF-8> (RuntimeError)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/utilities.rb:286:in `=~'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/utilities.rb:286:in `!~'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/utilities.rb:286:in `blank?'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/fields/common/common_address.rb:118:in `block in do_decode'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/fields/common/common_address.rb:118:in `reject'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/fields/common/common_address.rb:118:in `do_decode'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/fields/to_field.rb:51:in `decoded'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/fields/common/common_field.rb:27:in `to_s'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mail-2.6.6/lib/mail/field.rb:158:in `to_s'
/opt/zammad/app/models/channel/filter/identify_sender.rb:123:in `rescue in block in create_recipients'
/opt/zammad/app/models/channel/filter/identify_sender.rb:100:in `block in create_recipients'
/opt/zammad/app/models/channel/filter/identify_sender.rb:97:in `each'
/opt/zammad/app/models/channel/filter/identify_sender.rb:97:in `create_recipients'
/opt/zammad/app/models/channel/filter/identify_sender.rb:64:in `run'
/opt/zammad/app/models/channel/email_parser.rb:148:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:145:in `each'
/opt/zammad/app/models/channel/email_parser.rb:145:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:111:in `block in process'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:110:in `process'
/opt/zammad/app/models/channel/email_parser.rb:479:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:478:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:478:in `process_unprocessable_mails'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `eval'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
/opt/zammad/bin/rails:9:in `require'
/opt/zammad/bin/rails:9:in `<main>'
        from /opt/zammad/app/models/channel/email_parser.rb:108:in `process'
        from /opt/zammad/app/models/channel/email_parser.rb:479:in `block in process_unprocessable_mails'
        from /opt/zammad/app/models/channel/email_parser.rb:478:in `glob'
        from /opt/zammad/app/models/channel/email_parser.rb:478:in `process_unprocessable_mails'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `eval'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
        from /opt/zammad/bin/rails:9:in `require'
        from /opt/zammad/bin/rails:9:in `<main>'
```

I can submit the E-Mails wich are not processed, but not here.

What can we do to stop this from happening in the future?

 
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Could you please send one or two affected sample mails als eml-file to us?
support[at]zammad[dot]com - we'll check with our developers what the issue is and address it, if it's a bug. :-)

**Comment by MrGeneration** [comment]
Hey, 

thanks for the patience. This is actually a regression of #2224 .
@Dev: You can find  two working samples in #1043522 - if needed, ping Marcel or Thorsten. :)

**Comment by Dirk23** [comment]
So what does that mean?

**Comment by MrGeneration** [comment]
This means that we will address this when we find the time to do so.

**Comment by Dirk23** [comment]
Is there a way to "delete" the not processable Mails from Zammad?
![image](https://user-images.githubusercontent.com/4200682/58468579-17471280-813e-11e9-9222-972e7301bf61.png)

I already fixed the problems in these E-Mails and i dont need them any more.

**Comment by Dirk23** [comment]
Ok, i found it my self:

https://community.zammad.org/t/unprocessable-mails/779/5

Thank you anyways

**Comment by thorsteneckel** [comment]
The actual issue of the unprocessable mail is not resolved yet. Therefore I reopen the issue. Glad that it works now for you @Dirk23 👍 Let's get this fixed for the other installations out there.

**Comment by SummerStorm** [comment]
This is no longer reproducible on `develop` as of 48766c7db90f82b82e4ae7fe9e309a8e8a835093. 

The issue still exists on `stable`, but the next release is coming soon so the fix won't be backported.
