### ISSUE TITLE
Linking of external account in profile is broken

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2675]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1049778

### Expected behavior:

When trying to link a third party authentication like Google or Office365, you'll be redirected to the authentication site of the third party and then back to Zammad. Your accounts are now linked.

### Actual behavior:

When trying to link a third party authentication like Google or Office365, you can't be redirected because of error 404 for `/auth/authentication_provider`

### Reason:
The reason is this commit:
https://github.com/zammad/zammad/commit/9503ff20cefcfc39cb451562d7ec4fd440198564

We changed some security things for onniauth to protect Zammads users.
While we changed the behaviour (CSRF-Token in Header) for the login page, we forgot to fix this within the profile section as well.

### Steps to reproduce the behavior:

* try to link any third party account via profile to your Zammad-Account

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is fixed with the two commits above. Packages will be ready in about 30 minutes 🚀

**Comment by kominoshja** [comment]
Hi, uhm, are you sure this fixes it? I had to change the code (source install) since it still happens on latest .tar of zammad, and i still get 404 (maybe i need to restart something?)

**Comment by kominoshja** [comment]
@thorsteneckel Hi, uhm, are you sure this fixes it? I had to change the code (source install) since it still happens on latest .tar of zammad, and i still get 404 (maybe i need to restart something?)

**Comment by thorsteneckel** [comment]
Hi @kominoshja - the source tar files are not updated for each commit (as far as I'm aware of). We strongly encourage the usage of the OS packages. If you have any further questions please create a thread over at the [community board](http://community.zammad.org/) and refer to me.

**Comment by kominoshja** [comment]
Thanks for your answer. For those who are looking to add this to their source install, manually edit the files, recompile assets with rake, and restart zammad (and webserver maybe)
