### ISSUE TITLE
Deleted Google E-Mail-Account leads to Internal Server Error on Admin Channel Settings

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3392]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): Source
* Operating system: Ubuntu 18.04
* Database + version: PSQL 11
* Elasticsearch version: ES 7
* Ticket-ID: #1083494 

### Expected behavior:

* When a google account is deleted, I as an admin should be able to continue changing settings in the E-Mail and Google Channel section.

### Actual behavior:

* When a google account is deleted but still configured in Zammad (even if it is disabled?), I can no longer access the Channels settings page of at least E-Mail or Google.

### Monitoring and Logs

In the Monitoring section we first noticed it due to this message:
```
Failed to run scheduled job 'Delete obsolete classic IMAP backup.'. Cause: Failed to run ImapAuthenticationMigrationCleanupJob.perform_now after 10 tries #<RuntimeError: Failed to refresh XOAUTH2 access_token of provider 'google'! #<RuntimeError: Request failed! ERROR: invalid_grant (Account has been deleted)>>
```

An trying to access the E-Mail/Google Channel section produced this in `production.log`:
```
I, [2021-02-02T14:17:36.037353 #3590-70157872078520]  INFO -- : Started GET "/api/v1/channels_email?_=1612271255493" for 10.22.0.49 at 2021-02-02 14:17:36 +0100
I, [2021-02-02T14:17:36.042742 #3590-70157872078520]  INFO -- : Processing by ChannelsEmailController#index as JSON
I, [2021-02-02T14:17:36.042813 #3590-70157872078520]  INFO -- :   Parameters: {"_"=>"1612271255493"}
E, [2021-02-02T14:17:36.123753 #3590-70157872078520] ERROR -- : Request failed! ERROR: invalid_grant (Account has been deleted, params: {"client_id":"SOMECLIENTID.apps.googleusercontent.com","client_secret":"SOMESECRET","refresh_token":"SOMETOKEN","grant_type":"refresh_token"})
E, [2021-02-02T14:17:36.123950 #3590-70157872078520] ERROR -- : Request failed! ERROR: invalid_grant (Account has been deleted) (RuntimeError)
/var/www/zammad/releases/20201124110713/lib/external_credential/google.rb:221:in `refresh_token'
/var/www/zammad/releases/20201124110713/app/models/external_credential.rb:32:in `refresh_token'
/var/www/zammad/releases/20201124110713/app/models/channel.rb:342:in `refresh_xoaut2!'
/var/www/zammad/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
[... more gem stacktrace ...]
E, [2021-02-02T14:17:36.124877 #3590-70157872078520] ERROR -- : Failed to refresh XOAUTH2 access_token of provider 'google'! #<RuntimeError: Request failed! ERROR: invalid_grant (Account has been deleted)> (RuntimeError)
/var/www/zammad/releases/20201124110713/app/models/channel.rb:359:in `rescue in refresh_xoaut2!'
/var/www/zammad/releases/20201124110713/app/models/channel.rb:339:in `refresh_xoaut2!'
[... more gem stacktrace ...]
I, [2021-02-02T14:17:36.128438 #3590-70157872078520]  INFO -- : Completed 500 Internal Server Error in 86ms (Views: 0.2ms | ActiveRecord: 7.5ms)
```

### Steps to reproduce the behavior:

1. Configure Google OAuth
2. Create Google E-Mail Account
3. Configure Google Account in Zammad
4. Delete that Google Account at Google while it still is configured in Zammad

### How we fixed it:

1. Find Channel with the deleted E-Mail-Account
2. Drop that from the `channels` table
3. run `EmailAddress.channel_cleanup`

**Comment by MrGeneration** [comment]
Even worse, it doesn't just affect the UI but also seems the Channel fetch process to never get out of error state.
This means that the channel, even if it's set to `active: false` will keep on alerting during fetch and within Monitoring.

**Comment by MrGeneration** [comment]
Addition: This also causes Scheduler-Job `ImapAuthenticationMigrationCleanupJob.perform_now` (`Delete obsolete classic IMAP backup.`) to fail.

Edit:
Even running a `.find` on affected channels brings... features....


```
2.6.6 :002 > Channel.find(11)
Request failed! ERROR: invalid_grant (AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-11-09T12:57:20.5320943Z and was inactive for 90.00:00:00.
Trace ID: 3774d50a-b781-4174-b55e-8e3284d30c00
Correlation ID: 6a493877-e971-4b85-97d3-2e1b858b5fde
Timestamp: 2021-02-09 10:09:57Z, params: {"client_id":"YYYYY","client_secret":"ZZZZZZ","refresh_token":"XXXXXX","grant_type":"refresh_token"})
#<RuntimeError: Request failed! ERROR: invalid_grant (AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-11-09T12:57:20.5320943Z and was inactive for 90.00:00:00.
Trace ID: 3774d50a-b781-4174-b55e-8e3284d30c00
Correlation ID: 6a493877-e971-4b85-97d3-2e1b858b5fde
Timestamp: 2021-02-09 10:09:57Z)>
Traceback (most recent call last):
        3: from (irb):2
        2: from app/models/channel.rb:340:in `refresh_xoaut2!'
        1: from app/models/channel.rb:360:in `rescue in refresh_xoaut2!'
RuntimeError (Failed to refresh XOAUTH2 access_token of provider 'microsoft365'! #<RuntimeError: Request failed! ERROR: invalid_grant (AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-11-)9T12:57:20.5320943Z and was inactive for 90.00:00:00.
Trace ID: 3774d50a-b781-4174-b55e-8e3284d30c00
Correlation ID: 6a493877-e971-4b85-97d3-2e1b858b5fde
Timestamp: 2021-02-09 10:09:57Z)>
```

Above error also blocks `.destroy` and `.delete`.
This may be microsoft channel specific.

**Comment by thorsteneckel** [comment]
@mantas would you mind having a look?

**Comment by mantas** [comment]
@thorsteneckel @MrGeneration isn't this fixed by https://github.com/zammad/zammad/issues/3240 ?

**Comment by thorsteneckel** [comment]
I did a backport of #3240 and expect that @MrGeneration checked latest `3.6`. Can you confirm @MrGeneration ?

**Comment by MrGeneration** [comment]
> I did a backport of #3240 and expect that @MrGeneration checked latest 3.6. 

I double tabbed and pulled latest possible stable.
I can tell that the `active: false` issue seems to be gone.

However:
`ImapAuthenticationMigrationCleanupJob.perform_now` still fails.
Can't speak for the internal server errors as of now.

Edit: So all above statements I provided for everything but inactive channels during fetch still apply.

If @makmarius could double check, pull latest source version and verify it's still there (or not) that would be great!

**Comment by MrGeneration** [comment]
@thorsteneckel Mantas is on this topic.
I don't know what I should provide at this moment.

If something is missing, please let me know.

**Comment by MrGeneration** [comment]
After being pretty dump on pulling updates yesterday I re-checked.
My above statements do no longer apply to a latest stable version.

With a current version I revoked the token for my google account to cause authentication errors.
Above mentioned internal server error does not appear to me.

I currently expect this to be fixed.

If you still have issues, this may be a technical question.
Please consult the Community in that case: https://community.zammad.org.

If this proves to be a bug, we'll switch back to Github.

Thanks for understanding.

**Comment by thorsteneckel** [comment]
Duplicate of #3240
