### ISSUE TITLE
Error on sending E-Mails (incompatible encoding regexp match)

### ISSUE THREAD

**Issue by cwrm** [zammad/zammad#3552]
### Infos:

* Used Zammad version:4.0.0
* Installation method (source, package, ..): package
* Operating system: debian buster
* Database + version: postgresql-11
* Elasticsearch version: 7.12.1
* Browser + version: Firefox 88

### Expected behavior:

* Outgoing E-Mails should be sent via a postfix MTA (STARTTL, Submission)

### Actual behavior:

* Getting the following error message:
> Can't use Channel::Driver::Smtp: #<Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)>"

In the production log I found:
```
E, [2021-05-10T16:09:58.307351 #532-47340051469340] ERROR -- : Can't use Channel::Driver::Smtp: #<Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)>
/opt/zammad/app/models/channel/email_build.rb:92:in `match?'
/opt/zammad/app/models/channel/email_build.rb:92:in `block in build'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
[…]
```

After commenting out line 92 in File `/opt/zammad/app/models/channel/email_build.rb` and restarting Zammad, E-Mails are sent as expected. 

### Steps to reproduce the behavior:

* Commenting in the line 92 in File `/opt/zammad/app/models/channel/email_build.rb` on the system with the observed problem.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This was also posted within the community: https://community.zammad.org/t/sending-mails-failed-incompatible-encoding-regexp-match/6870

**Comment by Evoolo** [comment]
Facing the same Problem. 

After commenting out the line, do I need something else to run for this workaround?

**Comment by MrGeneration** [comment]
Sorry but we can't provide technical assistance on potential workarounds. We won't suggest to do so on productive systems.

**Comment by MrGeneration** [comment]
This must have appeared some where in between 04th May 2021 and 11th May 2021. 
Currently looking for possible evil commits.

Edit: Introduced by https://github.com/zammad/zammad/commit/a862a44bfc72102b0612db2c7fa943726960cbd6 / https://github.com/zammad/zammad/commit/9e157feb2a2b2464fe8d71dd1c09c1ee6ce21ce0

Affects both **stable** and develop.

**Comment by thorsteneckel** [comment]
Regression of https://github.com/zammad/zammad/issues/3529

**Comment by rolfschmidt** [comment]
workaround:
```dif
diff --git a/app/models/channel/email_build.rb b/app/models/channel/email_build.rb
index 1bc465ebc..c03b6074f 100644
--- a/app/models/channel/email_build.rb
+++ b/app/models/channel/email_build.rb
@@ -87,6 +87,7 @@ generate email with S/MIME

       # check if content-ids are used in body
       attr[:attachments]&.each do |attachment|
+        break
         next if attachment.instance_of?(Hash)
         next if attachment.preferences['Content-ID'].blank?
         next if !/<img [^>]* src="cid:#{Regexp.quote(attachment.preferences['Content-ID'])}" [^>]*>/xmsi.match?(html_alternative.body.to_s)
@@ -101,7 +102,7 @@ generate email with S/MIME
       attr[:attachments]&.each do |attachment|
         next if attachment.instance_of?(Hash)
         next if attachment.preferences['Content-ID'].blank?
-        next if !found_content_ids[ attachment.preferences['Content-ID'] ]
+        # next if !found_content_ids[ attachment.preferences['Content-ID'] ]

         attachment = Mail::Part.new do
           content_type attachment.preferences['Content-Type']
@@ -123,7 +124,7 @@ generate email with S/MIME
         attachment['content-id'] = nil
         mail.attachments[attachment[:filename]] = attachment
       else
-        next if attachment.preferences['Content-ID'].present? && found_content_ids[ attachment.preferences['Content-ID'] ]
+        next if attachment.preferences['Content-ID'].present? # && found_content_ids[ attachment.preferences['Content-ID'] ]

         filename = attachment.filename
         encoded_filename = Mail::Encodings.decode_encode filename, :encode
```

fix is in progress

**Comment by thorsteneckel** [comment]
Fixed via https://github.com/zammad/zammad/commit/be64e3ff0c263803def7bae342a79ef09c323f40 / https://github.com/zammad/zammad/commit/1949bee489c27f2cb92bd7901ff36e7a30bd0ab4 by reverting https://github.com/zammad/zammad/commit/a862a44bfc72102b0612db2c7fa943726960cbd6 / https://github.com/zammad/zammad/commit/9e157feb2a2b2464fe8d71dd1c09c1ee6ce21ce0

**Comment by MrGeneration** [comment]
Package built is running. This may take up to 120 minutes. This particular build can be watched here:
https://packager.io/gh/zammad/zammad/builds/5052

**Comment by InsaneSplash** [comment]
I updated to the latest Centos7 package just built and still have this error.
zammad-4.0.0-1620717869.89595964.centos7.x86_64

```
E, [2021-05-11T11:09:45.424219 #21043-47242929995380] ERROR -- : Can't use Channel::Driver::Smtp: #<Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)>
E, [2021-05-11T11:09:45.424461 #21043-47242929995380] ERROR -- : incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) (Encoding::CompatibilityError)
/opt/zammad/app/models/channel/email_build.rb:92:in `match?'
/opt/zammad/app/models/channel/email_build.rb:92:in `block in build'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel/email_build.rb:89:in `build'
/opt/zammad/app/models/channel/driver/smtp.rb:63:in `send'
/opt/zammad/app/models/channel.rb:257:in `deliver'
```

**Comment by martini** [comment]
@InsaneSplash it seems that the package is not the latest one. 

Your package:
> zammad-4.0.0-1620717869.89595964.centos7.x86_64
> Tue May 11 2021 07:24:29 GMT+0000

Its fixed in: 
> zammad-4.0.0-1620720320.1949bee4.centos7.x86_64.rpm
> Tue May 11 2021 08:05:20 GMT+0000

**Comment by flixr** [comment]
I also ran into this bug, upgraded to `4.0.0-1620720612.661989cc.buster` but 1h later the health check still shows the error and I didn't get any notification email for my test ticket created after the upgrade.

So apparently this is not completely fixed... or am I missing something?

**Comment by MrGeneration** [comment]
We no longer can reproduce this so you may want to check if affected files have been corrected.
See this commit: https://github.com/zammad/zammad/commit/1949bee489c27f2cb92bd7901ff36e7a30bd0ab4

**Comment by flixr** [comment]
Yes, I can confirm that the files are corrected.

I redid the email settings (haven't changed anything, just clicked through the existing/prefilled ones).
That seems to have done the trick...
