### ISSUE TITLE
Ticket hook not represented consistently inside a ticket with some articles

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3861]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): any
* Operating system: any 
* Database + version: any
* Elasticsearch version: any
* Browser + version: any 
* Ticket: #1096035

### Expected behavior:

* The representation of Zammad's "ticket hook" (e.g.: "Ticket#88006") should be consistent when shown in different places. 

### Actual behavior:

* The ticket hook below the ticket's title and it's representation in the top left corner (if a few articles exist in the ticket) differ in that the latter has a space character in it's name. Best shown in a screenshot: 

![image](https://user-images.githubusercontent.com/69846837/142878417-351cd36d-4315-45a2-95b2-24a1d6d352f1.png)

### Steps to reproduce the behavior:

* No action necessary. (Maybe create a few articles until it is possible to scroll and the ticket hook appears in the top left corner)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@rolfschmidt I think this is already fixed or? At least in `develop`.

**Comment by MrGeneration** [comment]
>  I think this is already fixed or? At least in develop.

I've had a look into the support instance and cannot support that claim. I can still see the issue.

**Comment by dominikklein** [comment]
Should be fixed only in develop with this commit: https://github.com/zammad/zammad/commit/bc431cb660e2ec3fc0a3a01611daf2f36f623793 (maybe the support instance has an older checkout).
