### ISSUE TITLE
Mails cannot be processed if the special character "+" is at the beginning of the sender address

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4731]
### Used Zammad Version

6.0.0

### Environment

- Installation method: package
- Operating system Debian 11.7
- Database + version:  postgresql-13
- Elasticsearch version: [e.g. 7.17]

### Actual behaviour

Mail addresses with the special character "+" at the beginning cannot be processed correctly by Zammad. The mails end up in unprocessable_mails on the system.

### Expected behaviour

Mails can be processed if the special character "+" appears at the beginning of the sender.

https://www.rfc-editor.org/rfc/rfc3696#section-3

### Steps to reproduce the behaviour

Send a mail with a "+" at the beginning of your Mail Adress to the ticket system

root@zdbg:/opt/zammad/var/spool/unprocessable_mail# cat f0b8014f57f0fd639ddc472a96625175.eml | zammad run rails r 'Channel::Driver::MailStdin.new'
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/f0b8014f57f0fd639ddc472a96625175.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '+markus@domain.de'>"
/opt/zammad/app/models/channel/email_parser.rb:141:in `rescue in process': #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '+markus@domain.de'> (RuntimeError)
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.4/lib/active_record/validations.rb:80:in `raise_validation_error'

and production.log

I, [2023-07-25T12:24:15.887529#213255-111520]  INFO -- : Process email with msgid '<2C521C1C-B23D-4F3B-8469-AAFA60D8F22C@blauring.de>'
E, [2023-07-25T12:24:15.915580#213255-111520] ERROR -- : can't run postmaster pre filter 0015_postmaster_filter_identify_sender: Channel::Filter::IdentifySender
E, [2023-07-25T12:24:15.915640#213255-111520] ERROR -- : #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '+markus@domain.de'>
E, [2023-07-25T12:24:15.916619#213255-111520] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/f0b8014f57f0fd639ddc472a96625175.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2023-07-25T12:24:15.916648#213255-111520] ERROR -- : Validation failed: Invalid email '+markus@domain.de' (ActiveRecord::RecordInvalid)

https://github.com/zammad/zammad/issues/4624
https://github.com/zammad/zammad/issues/4304

### Support Ticket

Ticket#10128855

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
@MarkusHeld is this issue already verified? What's the difference to https://github.com/zammad/zammad/issues/4304?

**Comment by fliebe92** [comment]
https://github.com/zammad/zammad/issues/4304 is fixed with Zammad 6.1. I guess there's no need for another issue...

**Comment by MarkusHeld** [comment]
@fliebe92 your right, i tested it on my instance and see that the error still exists but the Issues there closed. Now i know i have wait till 6.1. Thanks for the Information. I close the ticket now
