### ISSUE TITLE
Linked ticket state won't be updated

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#476]
The state of linked tickets is not updated automatically. 

![image](https://cloud.githubusercontent.com/assets/378324/20721201/52e823c8-b662-11e6-8396-5ee19791a38a.png)

The image shows a linked ticket which is closed

**Comment by hanneshal** [comment]
This should be fixed right now.

If not, please reopen.

**Comment by MrGeneration** [comment]
Sorry for digging that oldie out, but it's still reproducable within instances. :(
