### ISSUE TITLE
Error 500 from dl.packager.io

### ISSUE THREAD

**Issue by saschaludwig** [zammad/zammad#4912]
### Used Zammad Version

6.1.0

### Environment

Debian 11

### Actual behaviour

apt get can't download package list, resulting in an error 500

```
Err:1 https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 11/main amd64 zammad amd64 6.1.0-1698658720.d7dece56.bullseye
  500  Internal Server Error [IP: 178.63.71.248 443]
```

### Expected behaviour

apt can download package lists

### Steps to reproduce the behaviour

get update && get upgrade

### I'm sure this is a bug and no feature request or a general question.

kind of, may be related to dl.packager.io, but I don't know how to create an issue there, because I am not a customer of packager.io

**Comment by Alex-Giaquinto** [comment]
Having the exact same issue, came here to open a ticket and saw this was created 15 minutes ago. But identical situation as mine, just using Ubuntu 22.04

**Comment by MrGeneration** [comment]
This is not a Zammad specific issue but a packager.io one.
However, I contacted packager.io for you.

**Comment by crohr** [comment]
Hello, Packager.io maintainer here. There was a temporary issue affecting downloads yesterday afternoon, but it should have been resolved by now. Could you confirm it is back to normal?

**Comment by jakeh999** [comment]
@crohr It still seems to be having issues. I'm receiving the following error currently:
![Screenshot 2023-10-31 100817](https://github.com/zammad/zammad/assets/28597867/93593ebb-1c6c-44ee-abdc-43c133632bc6)

**Comment by saschaludwig** [comment]
> Hello, Packager.io maintainer here. There was a temporary issue affecting downloads yesterday afternoon, but it should have been resolved by now. Could you confirm it is back to normal?

Thanks for looking into that issue. Sadly it is still broken here:

```
Err:1 https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 11/main amd64 zammad amd64 6.1.0-1698658720.d7dece56.bullseye
  500  Internal Server Error [IP: 178.63.71.248 443]
```

**Comment by crohr** [comment]
Hello, you are correct, there was still an issue with the latest packages on the stable branch. Could you retry? Hopefully this time it is fixed.

Thanks

**Comment by saschaludwig** [comment]
> Hello, you are correct, there was still an issue with the latest packages on the stable branch. Could you retry? Hopefully this time it is fixed.
> Thanks

Yep, that looks better. `apt update && apt upgrade` and it works again.
Thank you very much for the fast response and the fix!

**Comment by crohr** [comment]
Great to hear, thanks for the feedback!

**Comment by TomAstor** [comment]
Hi, there seems to be having issues again. I'm seening the following error:
Fehl:1 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 18.04/main amd64 zammad amd64 6.1.0-1698658720.d7dece56.bionic
  500  Internal Server Error [IP: 178.63.71.248 443]
Maybe there is again a problem with the packager?

**Comment by crohr** [comment]
@TomAstor ubuntu 18.04 is EOL and it looks like packages for that distribution are no longer built by Zammad.

**Comment by MrGeneration** [comment]
> ubuntu 18.04 is EOL and it looks like packages for that distribution are no longer built by Zammad.

That is correct. But this shouldn't produce Error 500 right?

**Comment by TomAstor** [comment]
Thank you for your answers. I want to bring the system up to a reasonable level and before that I would like to upgrade to the latest version of Zammad from ubuntu 18.04. From my point of view, the packager should not throw an error message, but deliver the last package for this version ...

**Comment by Ddevrient41** [comment]
i have the same problem that when i give the install command for centOS 9 (i want to run it on Almalinux 9) after the add repository command, i get the same error with 404 and the ip @crohr

**Comment by TomAstor** [comment]
At least, this is how I managed to bring an old Zammad installation from Ubuntu 18.04 to 22.04. :


# change sources to specific version
nano /etc/apt/sources.list.d/zammad.list

# enter version after stable - here 6.1
deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-zammad.gpg] https://dl.packager.io/srv/deb/zammad/zammad/stable-6.1/ubuntu 18.04 main

# upgrade packages
apt update
apt upgrade


# run migration 
zammad run rake db:migrate
#restart zammad 
systemctl restart zammad


# dist upgrade
do-release-upgrade

# change sources to new ubuntu release 
nano /etc/apt/sources.list.d/zammad.list
deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-zammad.gpg] https://dl.packager.io/srv/deb/zammad/zammad/stable-6.1/ubuntu 20.04 main

# upgrade packages
apt update
apt upgrade

#upgrade postgres cluster 10 to 12

#show installed clusterversions
pg_lsclusters

#output:
10  main    5432 online postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
12  main    5433 online postgres /var/lib/postgresql/12/main /var/log/postgresql/postgresql-12-main.log

# remove secondary clustter
pg_dropcluster --stop 12 main
pg_upgradecluster 10 main /var/lib/postgresql/12/

# remove old cluster after migration
pg_dropcluster 10 main

# remove old packages
apt autoremove

#reboot system and check if service is running

#check service after reboot
systemctl status zammad

# change sources to new ubuntu release 
nano /etc/apt/sources.list.d/zammad.list
deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-zammad.gpg] https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 20.04 main


# upgrade packages
apt update
apt upgrade

# Upgrade Zammad fails - database migration error

# remove old database config files 
cd /opt/zammad/config/initializers
rm db_preferences_postgresql.rb
rm db_preferences_postgresql.rb

# run migration 
zammad run rake db:migrate

#restart zammad 
systemctl restart zammad


do-release-upgrade

nano /etc/apt/sources.list.d/zammad.list
deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-zammad.gpg] https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 22.04 main

#show installed clusterversions
pg_lsclusters

pg_dropcluster --stop 14 main
pg_upgradecluster 12 main /var/lib/postgresql/14/

# remove old cluster after migration
pg_dropcluster 12 main

-----------------------------------
# remove old packages 

dpkg -l | grep postgres

apt purge postgresql-10
apt purge postgresql-12

apt purge  postgresql-client-10
apt purge  postgresql-client-12
