### ISSUE TITLE
OTRS Importer problem with CAPITAL letters in email addresses

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#893]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu 16.4 LTS
* Browser + version: Chrome 56

### Scenario:

Import users from OTRS with email addresses like "Max.Muster@example.com". 

### Expected behavior:

* Convert it to max.muster@exmaple.com

### Actual behavior:

Imports email address "as is". Resulting problems:

You cannot login as "Max.Muster@example.com" because the login mask seems to compare the login in lowercase with email stored in the database (will never match).

If there is a OTRS article with "Max.Muster@example.com" and "max.muster@example.com" the importer creates two users.

### Steps to reproduce the behavior:

* Import e.g. "Max.Muster@example.com" from OTRS.

**Comment by thorsteneckel** [comment]
Fixed with the commit above. Will be part of the next release. Feedback would be great!

**Comment by thorsteneckel** [comment]
JFI: You can already test this when using the develop branch / package.

**Comment by hiaz** [comment]
@thorsteneckel I still see some MiXeD email addresses in the user table. I think the importer now does the right thing for emails of users which are extracted out of articles but not for users wich where "agents" in OTRS.

**Comment by thorsteneckel** [comment]
Thanks! I'll get on it.

**Comment by thorsteneckel** [comment]
Hi @hiaz - I've fixed that now for Customers and Agents, too. Glad to hear some feedback. Version should be ready in about 45 minutes from now.
