### ISSUE TITLE
Current date in date picker not highlighted

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#946]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: FF 49

### Expected behavior:

* Current date is highlighted in date picker

### Actual behavior:

* Current date not highlighted

### Steps to reproduce the behavior:

* Go into a ticket that already has "Wait till" (german: "Warten bis")
* Press Ctrl+F5 to simulate you've just logged into Zammad for the first time.
* Click the date field that already contains a date.
* Date picker opens, but only the today's date is highlighted, not the selected date.
* Go to another page / ticket.
* Go back to this ticket and click "date field" again. Again no highlight.

 Maybe there are also other circumstances to get a date picker with incorrect highlightning. I encountered this when fresh loading Zammad.

![screenshot-2017-04-12-18 54 28](https://cloud.githubusercontent.com/assets/26226303/24969697/e3f06e3a-1fb1-11e7-9fd4-fd5680c881aa.png)

**Comment by rolfschmidt** [comment]
Thanks you very much for your support @AND51 👍 Should be fixed with the next stable release.

**Comment by franz-xaver** [comment]
When the date picker is opened and no date is set 'today' is still not visible.
You'll have to click on 'today' and to reopen the date picker.

**Comment by franz-xaver** [comment]
![grafik](https://user-images.githubusercontent.com/38070915/60163367-bd4c7200-97fb-11e9-8c1a-f28294c86396.png)

**Comment by MrGeneration** [comment]
By now this is a duplicate of #2316

@franz-xaver thanks for your contribution.
Please don't get me wrong on the following:
Please don't search for every corner of the repo you find to state it's (still) broken.
This causes quite some noise for those who're following.

Stating it on one issue is enough :)
Anyway, thanks for letting us know, it's important!
